import 'package:shopio_app/features/home/data/models/product_model.dart';
import '../datasources/product_remote_datasource.dart';

abstract class ProductRepository {
  Future<ProductModel> addProduct(ProductModel product);
  Future<void> deleteProduct(String id);
}

class ProductRepositoryImpl implements ProductRepository {
  final ProductRemoteDataSource remoteDataSource;

  ProductRepositoryImpl({required this.remoteDataSource});

  @override
  Future<ProductModel> addProduct(ProductModel product) async {
    final productData = product.toJson();
    // Remove ID as it's generated by server/should be ignored for new items usually,
    // but DummyJSON might ignore it. We'll send what we have or clean it.
    // Ideally we send title, etc. toJson maps name -> title.

    return await remoteDataSource.addProduct(productData);
  }

  @override
  Future<void> deleteProduct(String id) async {
    await remoteDataSource.deleteProduct(id);
  }
}
